### ISSUE TITLE
Navier - Stokes Velocity Profile

### ISSUE THREAD

**Issue by stephanielue8088** [usfsoar/torito-23-24#31]
### Description
Develop a velocity profile with respect to radius (such that the reference is the center line of the orifice which is basically a cylindrical tube) in MATLAB

### Guidance 🤝
Step 1: Review and identify your dependent, independent and constant variables
Step 2: Convert your variables into METRIC. 
Step 3: Use MATLAB and the picture reference below to develop the Velocity Profile against radius,r
Step 4: Save your file as navier_stokes_yourname_VX where X is the version of your work

For example 
``` matlab
navier_stokes_steph_v1
```

Step 5: Upload your work to [Navier_Stokes_Injector Folder](https://usfedu.sharepoint.com/:f:/t/SocietyofAeronauticsandRocketryGRP/Eg9D8gYMeO5Aq7yg7ytsXJYBLXY_s3mmWstqqgP51FwQKg?e=uKorXc)

### Useful Information 💯 

Fluid: Water at room temperature
Chamber Pressure=100 psi 
Injector PressureDrop: 20% of the chamber pressure
Injector Orifice Length of the Oxidizer =  0.00299185 m 
Mass Flow of the Oxidizer = 0.0953266 kg/s 
Diameter of the Oxidizer Orifice =  0.000997284 m 

### Assumptions 🤔 

- Laminar Flow
- Constant viscosity and density
- Steady State
- Horizontal flow (no gravitational effects)
- Constant Temperature

![Image](https://github.com/usfsoar/torito-23-24/assets/136116008/fdcd4d38-a3ba-432b-9492-9379dce92cd8)

**Comment by stephanielue8088** [comment]
@kgary1 Here is what Faith and Juan will be working on. This is due next Tuesday March 5

**Comment by Face69** [comment]
I fried myself lel

**Comment by stephanielue8088** [comment]
Both codes have been uploaded 
Code to be revisited to sort our pressure drop challenge
